[package]
name = "paus"
version = "0.4.0"
edition = "2024"
description = "Third Time stopwatch daemon. Work as long as you want, earn break time as you go, spend it whenever."
readme = "README.md"
repository = "https://github.com/belovedEmperor/paus"
license = "MIT"
keywords = ["daemon", "productivity", "stopwatch", "timer", "waybar"]
categories = ["command-line-utilities"]

[dependencies]
anyhow = "1.0.103"
chrono = "0.4.45"
clap = { version = "4.6.1", features = ["derive"] }
dirs = "6.0.0"
ratatui = "0.30.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
tokio = { version = "1.52.3", features = [
  "io-util",
  "macros",
  "net",
  "rt-multi-thread",
  "signal",
] }

[lints.clippy]
# CORRECTNESS/STYLE/PERF
all = { level = "warn", priority = -1 }
arithmetic_side_effects = "deny"
as_conversions = "deny"
exit = "deny"
expect_used = "deny"
indexing_slicing = "deny"
# DEVELOPING LINTS
nursery = { level = "warn", priority = -1 }
panic = "deny"
panic_in_result_fn = "deny"
# UM, ACTUALLY
pedantic = { level = "deny", priority = -1 }
string_slice = "deny"
todo = "deny"
unchecked_time_subtraction = "deny"
unimplemented = "deny"
unreachable = "deny"
# DENY PANICS
unwrap_used = "deny"

[lints.rust]
unsafe_code = "deny"

elided_lifetimes_in_paths = "warn"
future_incompatible = { level = "warn", priority = -1 }
nonstandard_style = { level = "warn", priority = -1 }
rust_2018_idioms = { level = "warn", priority = -1 }
rust_2021_prelude_collisions = "warn"
semicolon_in_expressions_from_macros = "warn"
trivial_numeric_casts = "warn"
unexpected_cfgs = "warn"
unnameable_types = "warn"
# unreachable_pub = "warn"
unsafe_op_in_unsafe_fn = "warn"  # may become default: https://github.com/rust-lang/rust/issues/71668
unused_extern_crates = "warn"
unused_import_braces = "warn"
unused_lifetimes = "warn"
unused_macro_rules = "warn"

trivial_casts = "allow"
unused_qualifications = "allow"

[lints.rustdoc]
all = "warn"
missing_crate_level_docs = "warn"
# broken_intra_doc_links already covered by `all`
